version: "3"

services:
  db:
    image: postgres:16-alpine
    container_name: parte_db
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=app
  cache:
    image: "redis:7-alpine"
    container_name: parte_cache
    ports:
      - "127.0.0.1:6379:6379"