database:
  hostname: "localhost"
  port: 5432
  source: "postgres"
  user: "admin"
  password: "admin"
  database: "app"

http:
  hostname: "localhost"
  port: 8080
  readTimeout: "5s"
  writeTimeout: "10s"
  idleTimeout: "2m"
  tls:
    enabled: false
    certificate: ""
    key: ""

cache:
  hostname: "localhost"
  port: 6379
  password: ""

token:
  tokenkey: 0499a329d2c8c28f8724699daa380907

mail:
  sender: "Parte"
  password: "sxapyzdazbjfibov"
  senderAddress: "malibongwe2027zakes@gmail.com"